### ISSUE TITLE
NS2 Shine Admin mod in-game UI unable to scroll

### ISSUE THREAD

**Issue by zefleas** [Person8880/Shine#775] opened 2019-09-28 12:57 UTC
Unable to scroll down the player list in the UI.

This happened over a recent patch.
````

**Comment by zefleas** [comment] 2019-09-28 12:59
https://i.imgur.com/TjXGr9S.jpg

**Comment by Person8880** [comment] 2019-09-28 16:15
Looks like more than the scrolling is broken there. The text should not have artifacts like that.

Are there any script errors in the console when this happens? I tried to reproduce this by adding lots of bots in a listen server, but it scrolls fine (as do other lists such as the plugin list). Also, are you on Windows, or Linux with Proton?

**Comment by Person8880** [comment] 2019-09-29 13:01
Found the problem, it would only occur if the menu is opened when there are enough players to cause scrolling, not when players are added when it's already open. You should still be able to use the mouse wheel to scroll, it just makes the scrollbar's own size wrong.

It will be fixed in the next update.

**Closed by Person8880** 2019-09-29 13:01 UTC

**Comment by zefleas** [comment] 2019-09-30 15:15
sorry for the lack of reply,
The player names are censored out for privacy reasons.

Thanks for the fix on the next update!
