### ISSUE TITLE
sh_veto doesn't seem to work

### ISSUE THREAD

**Issue by Laaas** [Person8880/Shine#712] opened 2018-08-11 12:41 UTC
Configuration:
```json
{
	"AllowExtend": false,
	"AlwaysExtend": false,
	"BlockAfterRoundTimeInMinutes": 7,
	"ChangeDelayInSeconds": 5,
	"ChooseRandomOnTie": true,
	"ConsiderSimilarMapsAsExtension": true,
	"Constraints": {
		"MapVote": {
			"MinVotesRequired": {
				"Type": "PERCENT",
				"Value": 0
			},
			"MinVotesToFinish": {
				"Type": "PERCENT",
				"Value": 0.8
			}
		},
		"NextMapVote": {
			"MinVotesRequired": {
				"Type": "ABSOLUTE",
				"Value": 0
			},
			"MinVotesToFinish": {
				"Type": "PERCENT",
				"Value": 2
			}
		},
		"StartVote": {
			"MinPlayers": {
				"Type": "ABSOLUTE",
				"Value": 0
			},
			"MinVotesRequired": {
				"Type": "PERCENT",
				"Value": 0.51
			}
		}
	},
	"CycleOnEmpty": true,
	"DontExtend": [],
	"EmptyPlayerCount": 0,
	"EnableNextMapVote": true,
	"EnableRTV": true,
	"ExcludeLastMaps": {
		"Max": 4,
		"Min": 4,
		"UseStrictMatching": true
	},
	"ExtendTimeInMinutes": 15,
	"ForceChangeWhenSecondsLeft": 60,
	"ForceMenuOpenOnMapVote": true,
	"ForcedMaps": [],
	"GetMapsFromMapCycle": true,
	"IgnoreAutoCycle": {
		"gg_basic": true,
		"gg_mini_mario_2": true,
		"gg_shelter": true,
		"infest_biodome": true,
		"infest_caged": true,
		"infest_derelict": true,
		"infest_mineshaft": true,
		"infest_veil": true,
		"ns2_derelict": true,
		"ns2_kodiak": true
	},
	"Maps": {
		"ns2_biodome": true,
		"ns2_descent": true,
		"ns2_docking": true,
		"ns2_eclipse": true,
		"ns2_kodiak": true,
		"ns2_mineshaft": true,
		"ns2_refinery": true,
		"ns2_summit": true,
		"ns2_tram": true,
		"ns2_veil": true
	},
	"MaxExtends": 1,
	"MaxNominationsPerPlayer": 2,
	"MaxOptions": 8,
	"MaxRevotes": 3,
	"NextMapVoteMapTimeFraction": 1,
	"RoundLimit": 0,
	"ShowVoteChoices": false,
	"TieFails": false,
	"VoteDelayInMinutes": 2,
	"VoteLengthInMinutes": 0.9,
	"VoteSettings": {
		"AFKTimeInSeconds": 30,
		"ConsiderAFKPlayersInVotes": true
	},
	"VoteTimeoutInSeconds": 60,
	"__Version": "1.10"
}
```

**Comment by Person8880** [comment] 2018-08-11 18:07
What about it doesn't work? It only applies to map votes that were started by players, not the final vote for the next map.

**Comment by Laaas** [comment] 2018-08-11 18:11
Ohhhhh, that sounds very odd to me. Wouldn't !stopvote be better for that?

**Comment by Person8880** [comment] 2018-08-11 18:14
It doesn't stop the vote, it cancels the map change that is a result of a player-started vote.

**Comment by Person8880** [comment] 2018-08-18 17:42
Closing this as it does work as intended. If you want it to work differently feel free to open a new issue requesting a change.

**Closed by Person8880** 2018-08-18 17:42 UTC
