### ISSUE TITLE
evolve issue after update 335

### ISSUE THREAD

**Issue by hdcstfg** [Person8880/Shine#836] opened 2020-11-06 03:05 UTC
After NS2 update-335, techtree (j) seems to be disabled (no upgrades shown) for players who got shuffled onto the opposite team on start, therefore aliens can not evolve.
![bugged](https://user-images.githubusercontent.com/55025931/98321138-98b5fc00-1fe4-11eb-83c6-14daeca187bc.jpg)

Reproducible also without any other mods.
Trigger with setting:
VoteRandom.json:
    "AutoShuffleAtRoundStart": true,

**Comment by Person8880** [comment] 2020-11-06 17:35
Does this always happen? I can't reproduce this locally. With automatic shuffle enabled when I'm swapped from marines to aliens I can still open the tech tree and evolve (and the same for the other direction).

**Comment by hdcstfg** [comment] 2020-11-06 23:30
As i experienced sofar happened every time with every player who got shuffled onto the other team on startshuffle on our ranked server and on my test server.
It was experienced also on atleast one another ranked server.

**Comment by Person8880** [comment] 2020-11-07 10:42
When you tested it on your test server, was that with you alone? Or with a few other players? Also, not that it should make any difference, but what OS are the servers running on? 

I've tested both a listen server and a Windows dedicated server and both of them don't produce the issue when I'm alone on the server with bots. So I'm assuming that there's either some difference in OS (unlikely), or that it only happens when there's multiple players, or it only manifests with sufficient latency between the client and the server (my testing is all on the same machine so there's minimal latency).

**Comment by Person8880** [comment] 2020-11-07 11:01
Looking a bit further into the game code, it looks to me like changes in build 335 introduced a possible race condition in how the tech tree is updated. When the team is changed for a player, their tech tree is cleared both on the client and the server. However, the server is sending both a clear message, then a bunch of messages with the current tech tree state. If the client receives those before it realises it's changed team, it will end up clearing its tech tree locally and never receive the base state again.

This should be reported to the NS2 devs so they can fix it, there's not much I can do about it as it could happen even with a normal shuffle if the timing is bad.

**Comment by ironhorse86** [comment] 2020-11-08 01:18
We came to the same conclusions earlier today. We're aware and going to test a fix to it here soon. 
Feel free to close this

**Closed** 2020-11-08 10:38 UTC

**Comment by hdcstfg** [comment] 2020-11-08 12:08
thank you very much guys
